@Library("OpenEnclaveCommon") _
oe = new jenkins.common.Openenclave()

// The below timeout is set in minutes
GLOBAL_TIMEOUT = 7200


def win2016CrossCompile(String build_type) {
    stage("Windows ${build_type}") {
        node('SGXFLC-Windows') {
            timeout(GLOBAL_TIMEOUT) {
                cleanWs()
                checkout scm
                dir("build/X64-${build_type}") {
                  bat """
                      vcvars64.bat x64 && \
                      cmake.exe ${WORKSPACE} -G Ninja -DCMAKE_BUILD_TYPE=${build_type} -DBUILD_ENCLAVES=ON -Wdev && \
                      ninja.exe && \
                      ctest.exe -V -C ${build_type} --repeat-until-fail 5000
                      """
                }
            }
        }
    }
}


properties([buildDiscarder(logRotator(artifactDaysToKeepStr: '90',
                                      artifactNumToKeepStr: '180',
                                      daysToKeepStr: '90',
                                      numToKeepStr: '180')),
            [$class: 'JobRestrictionProperty']])

parallel "Win2016 Debug Cross Compile" :                        { win2016CrossCompile('Debug') },
         "Win2016 Release Cross Compile" :                      { win2016CrossCompile('Release') }
